### ISSUE TITLE
A Docker image not based from Alpine?

### ISSUE THREAD

**Issue by Glen-Moonpig** [docker-library/docker#199]
We are using docker:dind to build images on AWS m5 EC2 instances. Some of the images that we build are based on node and installing some node packages causes an error when the container doing the install is based on Alpine:

```bash
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:77:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:225:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:263:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:173:20)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:98
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^
TypeError: Cannot read property 'loaded' of undefined
    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
```

This would not be a problem if there was a docker image that is not based from Alpine as this is an Alpine-m5 specific issue. Does such an image exist?

**Comment by wglambert** [comment]
https://github.com/docker-library/docker/issues/146
>I've got https://hub.docker.com/r/tianon/docker-tianon and https://hub.docker.com/r/tianon/docker-master, which are both Debian-based (the former is based on https://github.com/tianon/docker-deb-vendored, the latter is based on builds from https://master.dockerproject.org/).
>
>If that's not good enough, it wouldn't be terribly hard to convert the relevant steps outlined in https://ram.tianon.xyz/post/2017/05/18/docker-setup-redux.html into a simple `Dockerfile`.

**Comment by Glen-Moonpig** [comment]
I think the docker image was likely not the real problem. I'm going to close this.
